events {}

http {
    log_format heartbleed_lab '$remote_addr - $time_local "$request" '
                              'status=$status uri="$request_uri" '
                              'referer="$http_referer" user_agent="$http_user_agent"';
    access_log /dev/stdout heartbleed_lab;

    server {
        listen 80;

        # Cấu hình điều hướng cho ứng dụng chính (Spring Boot)
        location / {
            return 302 /cve-heartbleed/;
        }

        # Cấu hình điều hướng cho mục tiêu CVE Heartbleed
        location /cve-heartbleed/ {
            proxy_pass https://heartbleed-server:443/;
            proxy_ssl_verify off; # Tắt xác minh chứng chỉ SSL giả của lab
        }
    }
}
